export const StorageKeys = {
  quitDate: "quitDate",
  cigsPerDay: "cigsPerDay",
  pricePerPack: "pricePerPack",
  cigsPerPack: "cigsPerPack",
  isPremium: "isPremium", // pour MVP sans RevenueCat
  language: "language",
  languagePreference: "languagePreference",
  currencyPreference: "currencyPreference",
  resolvedLanguage: "resolvedLanguage",
  resolvedCurrency: "resolvedCurrency",
  onboardingDone: "onboardingDone",
  notificationsEnabled: "notificationsEnabled",
  dailyCheckins: "dailyCheckins",
  pendingAction: "pendingAction",
  notificationTimes: "notificationTimes",
  shieldSessions: "shield_sessions",
  shieldWeekKey: "shield_weekKey",
  shieldWeekCount: "shield_weekCount",
  shieldTotalCompleted: "shield_totalCompleted",
  shieldVariantMode: "shield_variantMode",
  shieldSoundEnabled: "shield_sound_enabled",
  shieldDurationSec: "shield_duration_sec",
  journalEntries: "journal_entries",
  dailyStatusV1: "daily_status_v1",
  monthlyReportsV1: "monthly_reports_v1",
  monthlyReportNotifEnabled: "monthly_report_notif_enabled",
  monthlyReportNotifFeatureFlag: "monthly_report_notif_feature_flag",
  securityLockEnabled: "security_lock_enabled",
  securityBiometricPreferred: "security_biometric_preferred",
} as const;

export type StorageKey = typeof StorageKeys[keyof typeof StorageKeys];
